In [1]:
import numpy as np

In [2]:
x = np.arange(100000)

In [3]:
y = list(range(100000))

In [6]:
%time
for _ in range(10):
    x = x*2


CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 11 µs


In [7]:
%time
for _ in range(10):
    y = y*2

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.25 µs


In [9]:
data = np.random.randn(2,3)
data

array([[-1.79019031,  1.22631056,  0.93565513],
       [ 0.55100442,  0.9983459 , -1.38043707]])

In [10]:
data*10

array([[-17.9019031 ,  12.26310559,   9.35655129],
       [  5.51004416,   9.983459  , -13.80437068]])

In [11]:
data+data

array([[-3.58038062,  2.45262112,  1.87131026],
       [ 1.10200883,  1.9966918 , -2.76087414]])